wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 25
eps:
  value: 1.0e-06
hidden_size:
  value: 16
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.3
weight_ini:
  value: He Uniform
