wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 10
eps:
  value: 1.0e-06
hidden_size:
  value: 256
learning_rate:
  value: 0.003
loss:
  value: mean_squared_error
num_layers:
  value: 1
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: He Uniform
