wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 25
eps:
  value: 0.0001
hidden_size:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.0005
weight_ini:
  value: He Uniform
