wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.001
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weight_init:
  value: Xavier Normal
