wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 15
eps:
  value: 1.0e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.0004
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.4
weight_ini:
  value: He Normal
