wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 30
eps:
  value: 1.0e-06
hidden_size:
  value: 16
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.5
weight_ini:
  value: Xavier Normal
