wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 10
eps:
  value: 1.0e-06
hidden_size:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: momentum
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.005
weight_ini:
  value: Xavier Normal
