wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 256
dataset:
  value: fashion_mnist
epochs:
  value: 5
eps:
  value: 1.0e-06
hidden_size:
  value: 16
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.0001
weight_ini:
  value: He Uniform
