wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 5
eps:
  value: 0.0001
hidden_size:
  value: 16
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: momentum
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: Xavier Uniform
