wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709038443.65147
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
activation:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: fashion_mnist
epochs:
  desc: null
  value: 10
eps:
  desc: null
  value:
  - 0.0001
hidden_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value:
  - cross_entropy
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: rmsprop
weight_decay:
  desc: null
  value: 0.5
weight_init:
  desc: null
  value: random
