wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709016308.652511
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: random
