wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709412657.937936
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
    visualize:
      confusion_matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: confusion_matrix_table
                fields: []
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: fashion_mnist
epochs:
  desc: null
  value: 30
eps:
  desc: null
  value: 0.0001
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.003
loss:
  desc: null
  value: cross_entropy
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: nadam
wandb_project:
  desc: null
  value: cs23d014_assignment_1
weight_decay:
  desc: null
  value: 0.5
weight_ini:
  desc: null
  value: He Uniform
