wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 25
eps:
  value: 0.0001
hidden_size:
  value: 64
learning_rate:
  value: 0.0004
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0
weight_ini:
  value: He Normal
