wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709733207.425305
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
    visualize:
      confusion_matrix:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: confusion_matrix_table
                fields: []
