wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 25
eps:
  value: 0.0001
hidden_size:
  value: 128
learning_rate:
  value: 0.0004
loss:
  value: mean_squared_error
num_layers:
  value: 4
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0
weight_ini:
  value: He Uniform
