wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 15
eps:
  value: 0.0001
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: rmsprop
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.0001
weight_ini:
  value: Xavier Uniform
