wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 256
dataset:
  value: mnist
epochs:
  value: 10
eps:
  value: 0.0001
hidden_size:
  value: 16
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0
weight_ini:
  value: He Normal
