wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 25
eps:
  value: 0.0001
hidden_size:
  value: 256
learning_rate:
  value: 0.0004
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.2
weight_ini:
  value: Xavier Normal
