wandb_version: 1

activation:
  value: relu
batch_size:
  value: 256
dataset:
  value: mnist
epochs:
  value: 15
eps:
  value: 1.0e-06
hidden_size:
  value: 16
learning_rate:
  value: 0.003
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: He Uniform
