wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
eps:
  value: 1.0e-06
hidden_size:
  value: 32
learning_rate:
  value: 0.003
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.0005
weight_ini:
  value: He Normal
