wandb_version: 1

activation:
  value: relu
batch_size:
  value: 256
dataset:
  value: fashion_mnist
epochs:
  value: 20
eps:
  value: 0.0001
hidden_size:
  value: 64
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.5
weight_ini:
  value: He Normal
