wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 25
eps:
  value: 1.0e-06
hidden_size:
  value: 128
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.0001
weight_ini:
  value: Xavier Normal
