wandb_version: 1

activation:
  value: relu
batch_size:
  value: 256
dataset:
  value: fashion_mnist
epochs:
  value: 5
eps:
  value: 0.0001
hidden_size:
  value: 32
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: sigmoid
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0
weight_ini:
  value: He Normal
