wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 20
eps:
  value: 0.0001
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.1
weight_ini:
  value: He Normal
