wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 20
eps:
  value: 0.0001
hidden_size:
  value: 256
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: rmsprop
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0
weight_ini:
  value: Xavier Normal
