wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
eps:
  value: 1.0e-06
hidden_size:
  value: 64
learning_rate:
  value: 0.003
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: Xavier Uniform
