wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
eps:
  value: 1.0e-06
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nag
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.006
weight_ini:
  value: Xavier Normal
