wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 20
eps:
  value: 0.0001
hidden_size:
  value: 256
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: sgd
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: He Uniform
