wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 20
eps:
  value: 0.0001
hidden_size:
  value: 128
learning_rate:
  value: 0.003
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.3
weight_ini:
  value: Xavier Uniform
