wandb_version: 1

activation:
  value: relu
batch_size:
  value: 256
dataset:
  value: mnist
epochs:
  value: 25
eps:
  value: 1.0e-06
hidden_size:
  value: 16
learning_rate:
  value: 0.003
loss:
  value: mean_squared_error
num_layers:
  value: 1
optimizer:
  value: sgd
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: Xavier Uniform
