wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 25
eps:
  value: 0.0001
hidden_size:
  value: 32
learning_rate:
  value: 0.0004
loss:
  value: mean_squared_error
num_layers:
  value: 2
optimizer:
  value: nadam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: He Uniform
