wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
eps:
  value: 0.0001
hidden_size:
  value: 16
learning_rate:
  value: 0.0004
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: sgd
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.6
weight_ini:
  value: He Uniform
