wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
eps:
  value: 1.0e-06
hidden_size:
  value: 32
learning_rate:
  value: 0.003
loss:
  value: mean_squared_error
num_layers:
  value: 5
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0.2
weight_ini:
  value: He Uniform
