wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 5
eps:
  value: 1.0e-06
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
num_layers:
  value: 2
optimizer:
  value: adam
wandb_project:
  value: cs23d014_assignment_1
weight_decay:
  value: 0
weight_ini:
  value: He Normal
